Add Z3 to SV-COMP zip file

diff --git a/extra/svcomp/coastal-package b/extra/svcomp/coastal-package
--- a/extra/svcomp/coastal-package
+++ b/extra/svcomp/coastal-package
@@ -2,6 +2,11 @@
 
 DESTINATION=/tmp/coastal.zip
 PROJECTDIR=../..
+Z3EXEC=`type -p z3`
+if [ $? -ne 0 ] ; then
+	echo "Z3 not found!"
+	exit 1
+fi
 
 #------------------------------------------------------------------------------
 # determine the absolute project path
@@ -22,6 +27,8 @@ trap "rm -rf ${DIR}" EXIT
 #------------------------------------------------------------------------------
 mkdir -p ${DIR}/coastal/coastal
 cp -r ${PROJECTDIR}/build/install/coastal/lib ${DIR}/coastal/coastal/
+mkdir -p ${DIR}/coastal/coastal/z3
+cp ${Z3EXEC} ${DIR}/coastal/coastal/z3
 cp ${PROJECTDIR}/extra/svcomp/coastal-sv-comp ${DIR}/coastal/
 cp ${PROJECTDIR}/LICENSE.md ${DIR}/coastal/LICENSE
 SAVED="`pwd`"
